### ISSUE TITLE
research android basics

### ISSUE THREAD

**Issue by cpcampbe** [destin-estrela/SE308-winter2020-environmental-app#31]
-intents 
-activities
-context

Resources from Destin:
https://developer.android.com/guide/components/fundamentals

https://developer.android.com/jetpack/docs/guide

https://codelabs.developers.google.com/codelabs/build-your-first-android-app-kotlin/#0

**Comment by jhundal2021** [comment]
Research ways to log input from the user and visually represent the data history of the user.
